#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP1 -d I II III IV V VI VII VIII IX X

# For dual monitor
# bspc monitor eDP1 -d I II III IV V VI VII VIII IX
# bspc monitor HDMI2 -d X

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a '*:TEMPLATE' state=floating follow=on center=on
bspc rule -a '*:mgba' state=floating follow=on center=on
bspc rule -a kitty -o desktop="^1" && kitty &
bspc rule -a firefox -o desktop="^2" && firefox
# bspc rule -a TEMPLATE state=floating follow=on center=on
