#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule --add kitty --one-shot desktop="^1" && kitty
# why does this not work smh
bspc rule --add firefox --one-shot desktop="^2" && firefox
