# Instant escape
set -sg escape-time 0

# Use a modern terminfo
set -g default-terminal "tmux-256color"

# Allow truecolor passthrough
set -ga terminal-overrides ",*:Tc"

# Let apps know when they have focus
set -g focus-events on

set -g set-clipboard on

# enable mouse scrolling, does this have a perf impact?
set -g mouse on

set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g status on

set -g update-environment "SSH_AUTH_SOCK SSH_CONNECTION SSH_TTY DISPLAY"


# TODO: have a look at tmux-sensible
#
